-- ---------------------------------------------------------------------------
-- 010_vendor_category_services
--
-- A catalog of the services each vendor category offers (from vendor_services.txt), so choosing a
-- category on the vendor pages lists that category's services as checkboxes. Adds the categories
-- the list has that 009 did not. Vendors, their services and rates are untouched.
-- Take a phpMyAdmin export first.
-- ---------------------------------------------------------------------------

CREATE TABLE vendor_category_services (
  id          INT UNSIGNED NOT NULL AUTO_INCREMENT,
  category_id INT UNSIGNED NOT NULL,
  name        VARCHAR(150) NOT NULL,
  sort_order  INT          NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uq_vcs_name (category_id, name),
  CONSTRAINT fk_vcs_category FOREIGN KEY (category_id) REFERENCES vendor_categories (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Every category the services below belong to; existing ones are left as they are.
INSERT IGNORE INTO vendor_categories (name, sort_order) VALUES
  ('Catering', 10), ('Decoration', 20), ('Photography', 30), ('Videography', 40), ('Venue', 50),
  ('Sound & Lighting', 60), ('Transportation', 70), ('Entertainment', 80), ('Security', 90),
  ('Accommodation & Travel', 110),
  ('Staffing & Personnel', 120),
  ('Technology & Registration', 130),
  ('Marketing & Promotion', 140),
  ('Exhibition & Trade Show', 150),
  ('Rentals & Specialty Equipment', 160),
  ('Legal, Permits & Insurance', 170),
  ('Gifts & Merchandise', 180),
  ('Post-Event Services', 190);

INSERT INTO vendor_category_services (category_id, name, sort_order) VALUES
  ((SELECT id FROM vendor_categories WHERE name = 'Venue'), 'Banquet halls', 10),
  ((SELECT id FROM vendor_categories WHERE name = 'Venue'), 'Hotels', 20),
  ((SELECT id FROM vendor_categories WHERE name = 'Venue'), 'Convention centers', 30),
  ((SELECT id FROM vendor_categories WHERE name = 'Venue'), 'Outdoor grounds', 40),
  ((SELECT id FROM vendor_categories WHERE name = 'Venue'), 'Farmhouses', 50),
  ((SELECT id FROM vendor_categories WHERE name = 'Venue'), 'Marquees', 60),
  ((SELECT id FROM vendor_categories WHERE name = 'Venue'), 'Stage', 70),
  ((SELECT id FROM vendor_categories WHERE name = 'Venue'), 'Backdrops', 80),
  ((SELECT id FROM vendor_categories WHERE name = 'Venue'), 'Floor plans', 90),
  ((SELECT id FROM vendor_categories WHERE name = 'Venue'), 'Seating layouts', 100),
  ((SELECT id FROM vendor_categories WHERE name = 'Venue'), 'Chairs', 110),
  ((SELECT id FROM vendor_categories WHERE name = 'Venue'), 'Tables', 120),
  ((SELECT id FROM vendor_categories WHERE name = 'Venue'), 'Lounges', 130),
  ((SELECT id FROM vendor_categories WHERE name = 'Venue'), 'Podiums', 140),
  ((SELECT id FROM vendor_categories WHERE name = 'Venue'), 'Carpets', 150),
  ((SELECT id FROM vendor_categories WHERE name = 'Venue'), 'Tents and canopies', 160),
  ((SELECT id FROM vendor_categories WHERE name = 'Catering'), 'Buffet catering', 10),
  ((SELECT id FROM vendor_categories WHERE name = 'Catering'), 'Plated catering', 20),
  ((SELECT id FROM vendor_categories WHERE name = 'Catering'), 'Live stations', 30),
  ((SELECT id FROM vendor_categories WHERE name = 'Catering'), 'Menu design', 40),
  ((SELECT id FROM vendor_categories WHERE name = 'Catering'), 'Desserts', 50),
  ((SELECT id FROM vendor_categories WHERE name = 'Catering'), 'Cakes', 60),
  ((SELECT id FROM vendor_categories WHERE name = 'Catering'), 'Food trucks', 70),
  ((SELECT id FROM vendor_categories WHERE name = 'Catering'), 'Coffee carts', 80),
  ((SELECT id FROM vendor_categories WHERE name = 'Catering'), 'Mocktail / juice bar', 90),
  ((SELECT id FROM vendor_categories WHERE name = 'Catering'), 'Bartenders', 100),
  ((SELECT id FROM vendor_categories WHERE name = 'Catering'), 'Water supply', 110),
  ((SELECT id FROM vendor_categories WHERE name = 'Catering'), 'Tea and coffee service', 120),
  ((SELECT id FROM vendor_categories WHERE name = 'Catering'), 'Waiters', 130),
  ((SELECT id FROM vendor_categories WHERE name = 'Catering'), 'Chefs', 140),
  ((SELECT id FROM vendor_categories WHERE name = 'Catering'), 'Cleaners', 150),
  ((SELECT id FROM vendor_categories WHERE name = 'Catering'), 'Crockery and cutlery rental', 160),
  ((SELECT id FROM vendor_categories WHERE name = 'Decoration'), 'Centerpieces', 10),
  ((SELECT id FROM vendor_categories WHERE name = 'Decoration'), 'Floral arches', 20),
  ((SELECT id FROM vendor_categories WHERE name = 'Decoration'), 'Bouquets', 30),
  ((SELECT id FROM vendor_categories WHERE name = 'Decoration'), 'Stage flowers', 40),
  ((SELECT id FROM vendor_categories WHERE name = 'Decoration'), 'Custom backdrops', 50),
  ((SELECT id FROM vendor_categories WHERE name = 'Decoration'), 'Photo booths', 60),
  ((SELECT id FROM vendor_categories WHERE name = 'Decoration'), 'Props', 70),
  ((SELECT id FROM vendor_categories WHERE name = 'Decoration'), 'Signage', 80),
  ((SELECT id FROM vendor_categories WHERE name = 'Decoration'), 'Balloon decor', 90),
  ((SELECT id FROM vendor_categories WHERE name = 'Decoration'), 'Fairy lights', 100),
  ((SELECT id FROM vendor_categories WHERE name = 'Decoration'), 'Neon signs', 110),
  ((SELECT id FROM vendor_categories WHERE name = 'Decoration'), 'Chandeliers', 120),
  ((SELECT id FROM vendor_categories WHERE name = 'Decoration'), 'Banners', 130),
  ((SELECT id FROM vendor_categories WHERE name = 'Decoration'), 'Standees', 140),
  ((SELECT id FROM vendor_categories WHERE name = 'Decoration'), 'Flags', 150),
  ((SELECT id FROM vendor_categories WHERE name = 'Decoration'), 'Name tags', 160),
  ((SELECT id FROM vendor_categories WHERE name = 'Decoration'), 'Invitations', 170),
  ((SELECT id FROM vendor_categories WHERE name = 'Decoration'), 'Menus (printed)', 180),
  ((SELECT id FROM vendor_categories WHERE name = 'Decoration'), 'Programs (printed)', 190),
  ((SELECT id FROM vendor_categories WHERE name = 'Sound & Lighting'), 'Speakers', 10),
  ((SELECT id FROM vendor_categories WHERE name = 'Sound & Lighting'), 'Microphones', 20),
  ((SELECT id FROM vendor_categories WHERE name = 'Sound & Lighting'), 'Mixers', 30),
  ((SELECT id FROM vendor_categories WHERE name = 'Sound & Lighting'), 'Sound engineers', 40),
  ((SELECT id FROM vendor_categories WHERE name = 'Sound & Lighting'), 'Stage lighting', 50),
  ((SELECT id FROM vendor_categories WHERE name = 'Sound & Lighting'), 'Intelligent lights', 60),
  ((SELECT id FROM vendor_categories WHERE name = 'Sound & Lighting'), 'Spotlights', 70),
  ((SELECT id FROM vendor_categories WHERE name = 'Sound & Lighting'), 'Ambient lighting', 80),
  ((SELECT id FROM vendor_categories WHERE name = 'Sound & Lighting'), 'LED walls', 90),
  ((SELECT id FROM vendor_categories WHERE name = 'Sound & Lighting'), 'Projectors', 100),
  ((SELECT id FROM vendor_categories WHERE name = 'Sound & Lighting'), 'Screens', 110),
  ((SELECT id FROM vendor_categories WHERE name = 'Sound & Lighting'), 'Live streaming', 120),
  ((SELECT id FROM vendor_categories WHERE name = 'Sound & Lighting'), 'Recording', 130),
  ((SELECT id FROM vendor_categories WHERE name = 'Sound & Lighting'), 'Generators', 140),
  ((SELECT id FROM vendor_categories WHERE name = 'Sound & Lighting'), 'Truss systems', 150),
  ((SELECT id FROM vendor_categories WHERE name = 'Sound & Lighting'), 'Stage platforms', 160),
  ((SELECT id FROM vendor_categories WHERE name = 'Sound & Lighting'), 'Cabling', 170),
  ((SELECT id FROM vendor_categories WHERE name = 'Sound & Lighting'), 'Technical crew', 180),
  ((SELECT id FROM vendor_categories WHERE name = 'Entertainment'), 'DJs', 10),
  ((SELECT id FROM vendor_categories WHERE name = 'Entertainment'), 'Live bands', 20),
  ((SELECT id FROM vendor_categories WHERE name = 'Entertainment'), 'Singers', 30),
  ((SELECT id FROM vendor_categories WHERE name = 'Entertainment'), 'Dancers', 40),
  ((SELECT id FROM vendor_categories WHERE name = 'Entertainment'), 'Comedians', 50),
  ((SELECT id FROM vendor_categories WHERE name = 'Entertainment'), 'Magicians', 60),
  ((SELECT id FROM vendor_categories WHERE name = 'Entertainment'), 'MCs / emcees', 70),
  ((SELECT id FROM vendor_categories WHERE name = 'Entertainment'), 'Anchors', 80),
  ((SELECT id FROM vendor_categories WHERE name = 'Entertainment'), 'Keynote speakers', 90),
  ((SELECT id FROM vendor_categories WHERE name = 'Entertainment'), 'Celebrity appearances', 100),
  ((SELECT id FROM vendor_categories WHERE name = 'Entertainment'), 'Games and activities', 110),
  ((SELECT id FROM vendor_categories WHERE name = 'Entertainment'), 'Kids'' entertainers', 120),
  ((SELECT id FROM vendor_categories WHERE name = 'Entertainment'), 'Cultural shows', 130),
  ((SELECT id FROM vendor_categories WHERE name = 'Photography'), 'Candid photography', 10),
  ((SELECT id FROM vendor_categories WHERE name = 'Photography'), 'Formal photography', 20),
  ((SELECT id FROM vendor_categories WHERE name = 'Photography'), 'Event coverage', 30),
  ((SELECT id FROM vendor_categories WHERE name = 'Photography'), 'Drone footage', 40),
  ((SELECT id FROM vendor_categories WHERE name = 'Photography'), '360° booth', 50),
  ((SELECT id FROM vendor_categories WHERE name = 'Photography'), 'Photo kiosks', 60),
  ((SELECT id FROM vendor_categories WHERE name = 'Photography'), 'Photo editing', 70),
  ((SELECT id FROM vendor_categories WHERE name = 'Photography'), 'Albums', 80),
  ((SELECT id FROM vendor_categories WHERE name = 'Photography'), 'Same-day edits', 90),
  ((SELECT id FROM vendor_categories WHERE name = 'Videography'), 'Event videography', 10),
  ((SELECT id FROM vendor_categories WHERE name = 'Videography'), 'Cinematic videography', 20),
  ((SELECT id FROM vendor_categories WHERE name = 'Videography'), 'Drone videography', 30),
  ((SELECT id FROM vendor_categories WHERE name = 'Videography'), 'Highlight reels', 40),
  ((SELECT id FROM vendor_categories WHERE name = 'Videography'), 'Video editing', 50),
  ((SELECT id FROM vendor_categories WHERE name = 'Videography'), 'Same-day video edits', 60),
  ((SELECT id FROM vendor_categories WHERE name = 'Transportation'), 'Shuttles', 10),
  ((SELECT id FROM vendor_categories WHERE name = 'Transportation'), 'Buses', 20),
  ((SELECT id FROM vendor_categories WHERE name = 'Transportation'), 'Limousines', 30),
  ((SELECT id FROM vendor_categories WHERE name = 'Transportation'), 'Valet parking', 40),
  ((SELECT id FROM vendor_categories WHERE name = 'Transportation'), 'Cargo', 50),
  ((SELECT id FROM vendor_categories WHERE name = 'Transportation'), 'Loading and unloading', 60),
  ((SELECT id FROM vendor_categories WHERE name = 'Transportation'), 'Warehousing', 70),
  ((SELECT id FROM vendor_categories WHERE name = 'Transportation'), 'Airport transfers', 80),
  ((SELECT id FROM vendor_categories WHERE name = 'Transportation'), 'Fleet management', 90),
  ((SELECT id FROM vendor_categories WHERE name = 'Security'), 'Security guards', 10),
  ((SELECT id FROM vendor_categories WHERE name = 'Security'), 'Crowd control', 20),
  ((SELECT id FROM vendor_categories WHERE name = 'Security'), 'Bag checks', 30),
  ((SELECT id FROM vendor_categories WHERE name = 'Security'), 'VIP protection', 40),
  ((SELECT id FROM vendor_categories WHERE name = 'Accommodation & Travel'), 'Hotel room blocks (guests)', 10),
  ((SELECT id FROM vendor_categories WHERE name = 'Accommodation & Travel'), 'Speaker and VIP accommodation', 20),
  ((SELECT id FROM vendor_categories WHERE name = 'Accommodation & Travel'), 'Flights', 30),
  ((SELECT id FROM vendor_categories WHERE name = 'Accommodation & Travel'), 'Visas', 40),
  ((SELECT id FROM vendor_categories WHERE name = 'Accommodation & Travel'), 'Itineraries', 50),
  ((SELECT id FROM vendor_categories WHERE name = 'Staffing & Personnel'), 'Ushers', 10),
  ((SELECT id FROM vendor_categories WHERE name = 'Staffing & Personnel'), 'Hostesses', 20),
  ((SELECT id FROM vendor_categories WHERE name = 'Staffing & Personnel'), 'Registration desk teams', 30),
  ((SELECT id FROM vendor_categories WHERE name = 'Staffing & Personnel'), 'Coordinators', 40),
  ((SELECT id FROM vendor_categories WHERE name = 'Staffing & Personnel'), 'Paramedics', 50),
  ((SELECT id FROM vendor_categories WHERE name = 'Staffing & Personnel'), 'Ambulance standby', 60),
  ((SELECT id FROM vendor_categories WHERE name = 'Staffing & Personnel'), 'Pre-event cleaning', 70),
  ((SELECT id FROM vendor_categories WHERE name = 'Staffing & Personnel'), 'During-event cleaning', 80),
  ((SELECT id FROM vendor_categories WHERE name = 'Staffing & Personnel'), 'Post-event cleaning', 90),
  ((SELECT id FROM vendor_categories WHERE name = 'Technology & Registration'), 'Online ticketing', 10),
  ((SELECT id FROM vendor_categories WHERE name = 'Technology & Registration'), 'QR codes', 20),
  ((SELECT id FROM vendor_categories WHERE name = 'Technology & Registration'), 'Check-in systems', 30),
  ((SELECT id FROM vendor_categories WHERE name = 'Technology & Registration'), 'Event app: agenda', 40),
  ((SELECT id FROM vendor_categories WHERE name = 'Technology & Registration'), 'Event app: networking', 50),
  ((SELECT id FROM vendor_categories WHERE name = 'Technology & Registration'), 'Polls and Q&A', 60),
  ((SELECT id FROM vendor_categories WHERE name = 'Technology & Registration'), 'Webinar tools', 70),
  ((SELECT id FROM vendor_categories WHERE name = 'Technology & Registration'), 'Streaming platform', 80),
  ((SELECT id FROM vendor_categories WHERE name = 'Technology & Registration'), 'Interpretation', 90),
  ((SELECT id FROM vendor_categories WHERE name = 'Technology & Registration'), 'RFID', 100),
  ((SELECT id FROM vendor_categories WHERE name = 'Technology & Registration'), 'Badge printing', 110),
  ((SELECT id FROM vendor_categories WHERE name = 'Technology & Registration'), 'Data and analytics', 120),
  ((SELECT id FROM vendor_categories WHERE name = 'Marketing & Promotion'), 'Press releases', 10),
  ((SELECT id FROM vendor_categories WHERE name = 'Marketing & Promotion'), 'Media invitations', 20),
  ((SELECT id FROM vendor_categories WHERE name = 'Marketing & Promotion'), 'Social media campaigns', 30),
  ((SELECT id FROM vendor_categories WHERE name = 'Marketing & Promotion'), 'Influencers', 40),
  ((SELECT id FROM vendor_categories WHERE name = 'Marketing & Promotion'), 'Email marketing', 50),
  ((SELECT id FROM vendor_categories WHERE name = 'Marketing & Promotion'), 'Graphic design', 60),
  ((SELECT id FROM vendor_categories WHERE name = 'Marketing & Promotion'), 'Copywriting', 70),
  ((SELECT id FROM vendor_categories WHERE name = 'Marketing & Promotion'), 'Content videography', 80),
  ((SELECT id FROM vendor_categories WHERE name = 'Marketing & Promotion'), 'Sponsorship coordination', 90),
  ((SELECT id FROM vendor_categories WHERE name = 'Marketing & Promotion'), 'Partnership coordination', 100),
  ((SELECT id FROM vendor_categories WHERE name = 'Exhibition & Trade Show'), 'Modular stands', 10),
  ((SELECT id FROM vendor_categories WHERE name = 'Exhibition & Trade Show'), 'Custom booth builds', 20),
  ((SELECT id FROM vendor_categories WHERE name = 'Exhibition & Trade Show'), 'Freight handling', 30),
  ((SELECT id FROM vendor_categories WHERE name = 'Exhibition & Trade Show'), 'Customs handling', 40),
  ((SELECT id FROM vendor_categories WHERE name = 'Exhibition & Trade Show'), 'Product demo specialists', 50),
  ((SELECT id FROM vendor_categories WHERE name = 'Exhibition & Trade Show'), 'Lead retrieval systems', 60),
  ((SELECT id FROM vendor_categories WHERE name = 'Rentals & Specialty Equipment'), 'Air conditioners', 10),
  ((SELECT id FROM vendor_categories WHERE name = 'Rentals & Specialty Equipment'), 'Heaters', 20),
  ((SELECT id FROM vendor_categories WHERE name = 'Rentals & Specialty Equipment'), 'Coolers', 30),
  ((SELECT id FROM vendor_categories WHERE name = 'Rentals & Specialty Equipment'), 'Fans', 40),
  ((SELECT id FROM vendor_categories WHERE name = 'Rentals & Specialty Equipment'), 'Portable restrooms', 50),
  ((SELECT id FROM vendor_categories WHERE name = 'Rentals & Specialty Equipment'), 'Luxury restrooms', 60),
  ((SELECT id FROM vendor_categories WHERE name = 'Rentals & Specialty Equipment'), 'Fireworks', 70),
  ((SELECT id FROM vendor_categories WHERE name = 'Rentals & Specialty Equipment'), 'Pyrotechnics', 80),
  ((SELECT id FROM vendor_categories WHERE name = 'Rentals & Specialty Equipment'), 'Fog effects', 90),
  ((SELECT id FROM vendor_categories WHERE name = 'Rentals & Specialty Equipment'), 'Confetti', 100),
  ((SELECT id FROM vendor_categories WHERE name = 'Rentals & Specialty Equipment'), 'Cold sparks', 110),
  ((SELECT id FROM vendor_categories WHERE name = 'Rentals & Specialty Equipment'), 'Tents', 120),
  ((SELECT id FROM vendor_categories WHERE name = 'Rentals & Specialty Equipment'), 'Flooring', 130),
  ((SELECT id FROM vendor_categories WHERE name = 'Rentals & Specialty Equipment'), 'Dance floors', 140),
  ((SELECT id FROM vendor_categories WHERE name = 'Rentals & Specialty Equipment'), 'Generators (rental)', 150),
  ((SELECT id FROM vendor_categories WHERE name = 'Legal, Permits & Insurance'), 'Permit consultants', 10),
  ((SELECT id FROM vendor_categories WHERE name = 'Legal, Permits & Insurance'), 'Noise clearance', 20),
  ((SELECT id FROM vendor_categories WHERE name = 'Legal, Permits & Insurance'), 'Fire clearance', 30),
  ((SELECT id FROM vendor_categories WHERE name = 'Legal, Permits & Insurance'), 'Liability insurance', 40),
  ((SELECT id FROM vendor_categories WHERE name = 'Legal, Permits & Insurance'), 'Cancellation insurance', 50),
  ((SELECT id FROM vendor_categories WHERE name = 'Legal, Permits & Insurance'), 'Weather coverage', 60),
  ((SELECT id FROM vendor_categories WHERE name = 'Legal, Permits & Insurance'), 'Contract advice', 70),
  ((SELECT id FROM vendor_categories WHERE name = 'Legal, Permits & Insurance'), 'IP and copyright (music licensing)', 80),
  ((SELECT id FROM vendor_categories WHERE name = 'Gifts & Merchandise'), 'Corporate gifts', 10),
  ((SELECT id FROM vendor_categories WHERE name = 'Gifts & Merchandise'), 'Custom merchandise', 20),
  ((SELECT id FROM vendor_categories WHERE name = 'Gifts & Merchandise'), 'Souvenirs', 30),
  ((SELECT id FROM vendor_categories WHERE name = 'Gifts & Merchandise'), 'Wedding favors', 40),
  ((SELECT id FROM vendor_categories WHERE name = 'Gifts & Merchandise'), 'Awards and trophies', 50),
  ((SELECT id FROM vendor_categories WHERE name = 'Gifts & Merchandise'), 'Engraving', 60),
  ((SELECT id FROM vendor_categories WHERE name = 'Gifts & Merchandise'), 'Certificates', 70),
  ((SELECT id FROM vendor_categories WHERE name = 'Post-Event Services'), 'Teardown and dismantling', 10),
  ((SELECT id FROM vendor_categories WHERE name = 'Post-Event Services'), 'Waste management', 20),
  ((SELECT id FROM vendor_categories WHERE name = 'Post-Event Services'), 'Recycling', 30),
  ((SELECT id FROM vendor_categories WHERE name = 'Post-Event Services'), 'Feedback and survey tools', 40),
  ((SELECT id FROM vendor_categories WHERE name = 'Post-Event Services'), 'Reporting and ROI analysis', 50);

INSERT INTO schema_version (version) VALUES (10);
